[[$head]]
</head>
<body>
<header>
    [[$menu]]
</header>
[[$contact_chank]]
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDuKGM5Uyp8zEcgsODy7nxVwFIEgEgLJ_k"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="assets/js/bootstrap.min.js"></script>

<script type="text/javascript" src="assets/js/script.js"></script>

<script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="assets/plagins/slick/slick/slick.min.js"></script>
</body>
</html>