[[$head]]
</head>
<body>
<header>
    [[$menu]]
</header>
<section class="main">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-lg-offset-5">
                <img class="logo" src="assets/images/flat_logo.png" alt="логотип">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-1 col-lg-offset-6">
                <div class="line"></div>
                <div class="rhomb"></div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <h1>Квартиры посуточно <br>в Киеве</h1>
            </div>
        </div>
    </div>
    <form id="main-filter-apartment">
        <div class="container one">
            <div class="row">
                [[!main-filter-init]]
                <div class="col-lg-12 make_position">
                    <div class="choose1">
                        <p class="labell">дата посещения</p>
                        <div class="calendar">
                            <p>11.02/13.02.2017</p>
                        </div>
                    </div>
                    <div class="choose2">
                        <p class="labell">количество комнат</p>
                        <input type="checkbox" id="room-1" name="rooms[]" value="1"/>
                        <label for="room-1"><span></span></label>
                        <input type="checkbox" id="room-2" name="rooms[]" value="2"/>
                        <label for="room-2"><span></span></label>
                        <input type="checkbox" id="room-3" name="rooms[]" value="3"/>
                        <label for="room-3"><span></span></label>
                        <input type="checkbox" id="room-4" name="rooms[]" value=":>=:4"/>
                        <label for="room-4"><span></span></label>
                    </div>
                    <div class="choose3">
                        <div>
                            <p class="labell">стоимость</p>
                            <input type="checkbox" id="price-one" name="price" value=":<<:[[#6.price-from]]"/>
                            <label for="price-one"><span></span></label>
                            <input type="checkbox" id="price-two" name="price"
                                   value=":>=:[[#6.price-from]]||:<=:[[#6.price-from-to]]"/>
                            <label for="price-two"><span></span></label>
                            <input type="checkbox" id="price-three" name="price" value=":>>:[[#6.price-from-to]]"/>
                            <label for="price-three"><span></span></label>
                        </div>
                        <div>
                            <p class="labell">все</p>
                            <button><img src="assets/images/yes.png"></button>
                        </div>
                    </div>
                </div>
            </div>
            <a href="#" class="additional">дополнительные параметры <img src="assets/images/arrow.png"></a>
            <div class="row show_add">
                <div class="col-lg-12">
                    <div class="choose4">
                        <div class="form-group">
                            <label for="exampleSelect1">метро</label>
                            <select class="form-control" id="exampleSelect1" name="metro[]" multiple>
                                [[+metro_options]]
                            </select>
                        </div>
                    </div>
                    <div class="choose4">
                        <div class="form-group">
                            <label for="exampleSelect1">улица</label>
                            <select class="form-control" id="exampleSelect1" name="street[]" >
                                [[+street_options]]
                            </select>
                        </div>
                    </div>
                    <div class="choose4">
                        <div class="form-group">
                            <label for="exampleSelect1">удобства</label>
                            <select class="form-control" id="exampleSelect1" name="facilities[]" >
                                [[+facilites_options]]
                            </select>
                        </div>
                    </div>
                    <div class="choose4">
                        <div class="form-group">
                            <label for="exampleSelect1">дополнительно</label>
                            <select class="form-control" id="exampleSelect1" name="addition[]" placeholder="Выбрать">
                                [[+additional_rules]]
                            </select>
                        </div>
                    </div>
                </div>
                <a href="#" class="additional">свернуть <img src="assets/images/arrow_up.png"></a>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-lg-offset-5">
                    <div class="but_border">
                        <button class="select">Подобрать</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="assets/js/script.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="assets/plagins/slick/slick/slick.min.js"></script>
</body>
</html>