[[$head]]

</head>
<body>
<header>
    [[$menu]]
</header>

[[*id:in=`50`:then=`[[$rules_chank?&del=`*`]]`]]
[[*id:in=`51`:then=`[[$about_chank?&del=`*`]]`]]
[[*id:in=`52`:then=`[[$turistam_chank?&del=`*`]]`]]
[[*id:in=`65`:then=`[[$news_chank?&del=`*`]]`]]

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="assets/js/script.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="assets/plagins/slick/slick/slick.min.js"></script>
</body>
</html>

